server:
  port: 8081

spring:
  datasource:
    name: task
    url: jdbc:mysql://127.0.0.1:3306/task?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: zkt123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



mybatis:
  type-aliases-package: com.erik.erikdemo.bean.*
  #mapper-locations: classpath:mappers/*.xmls
